services:
  # Main web application
  - type: web
    name: momentum-ai-web
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        value: AIzaSyC6ENhmUrrtrN6HFbudthifGwUGSzWih7A
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        value: aviatoronline-6c2b4.firebaseapp.com
      - key: NEXT_PUBLIC_FIREBASE_DATABASE_URL
        value: https://aviatoronline-6c2b4-default-rtdb.firebaseio.com
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        value: aviatoronline-6c2b4
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        value: aviatoronline-6c2b4.firebasestorage.app
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        value: "471392622297"
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        value: 1:471392622297:web:95dca8c181277d3526d0c8
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: MAIN_TREASURY_ADDRESS
        value: TYour1MainTronAddressHere123456789012345
      - key: ADMIN_SECRET_KEY
        generateValue: true
